### PR TITLE
Database Models

### LINKED ISSUE #2: create base models
- users
- trash
- userstrash

### PR DESCRIPTION
**Pull request by AnthonyKrueger**
added Trash, User, and UsersTrash tables along with relationships

-fixes #2

### CODE REVIEW

**Review by Proto133 — APPROVED** [review]
Using Class extends model huh?

**Review by jquanisha — APPROVED** [review]
LGTM

**Review by GPLOTKE — COMMENTED** [review]
noice

**Comment by AnthonyKrueger** [comment]
> Using Class extends model huh?

I like adding methods this way better, issa new thing Im trying out

**Pull request merged**
